apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broadcast-pod
$patch: strategic
spec:
  template:
    spec:
      containers:
        - name: broadcast-container
          env:
            - name: BROADCAST_MODE
              value: "log_only"
