apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
  namespace: project
spec:
  template:
    spec:
      containers:
        - name: broadcast-container
          env:
            - name: BROADCAST_MODE
              value: "log_only"
