apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dep #link to deployment
  namespace: exercises
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
