apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: project
spec:
  storageClassName: project-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
